<?


$mode = gpc('mode');
if (($mode == 'fiche' || $mode == 'bdd') && gpc('id') > 0) {
	$id = gpc('id');
	$A =& new Q("SELECT rubrique_id FROM mod_shopping WHERE id='".$id."' LIMIT 1");
	$rub_id = intval($A->V[0]['rubrique_id']);
	if ($rub_id < 1) $boutonFiche = '<strong>ATTENTION : vous n\'avez pas défini de rubrique(s) pour votre article</strong>';
	else {
		$previewf = $WWW.'article-r'.$rub_id.'-a'.$id.'.html';
	}
}


// -------------------- PRODUITS --------------------------- // 
$R1 = array(
	'table'=>					'mod_shopping',
	'titre'=>					'Article shopping',
	'titres'=>					'Articles shopping',
	'genre'=>					'',
	'relation'=>				'',//'parent:1',
	'rubrelation'=>				'',
	'childRel'=>				'',
	'rubLevel'=>				'',
	'prodLevel'=>				'',
	'wherenot'=>				'',
	'postbdd'=>					'',
	'preview'=>					'',
	'previewf'=>				$previewf,
	'ifr '=>					'',
	'boutonFiche'=>				$boutonFiche,
	'boutonListe'=>				'',
	'filtre'=>					array('statut'=>'todo', 'utilisateur_id'=>($_SESSION[SITE_CONFIG]['ADMIN']['type'] != '3' ? $_SESSION[SITE_CONFIG]['ADMIN']['id'] : 'todo'), 'rubrique_id'=>'todo'),
	'ordre'=>					'datepub DESC',
	'miseenavant'=>				'',
	'fixe'=>					'',
	'tips'=>				'<br />Vous pouvez prévisualiser votre article dans le site avant que celui si ne soit publié (statut = Valide)',
	'rep'=>						$rep.'shopping/',
	'sizeimg'=>					$arr_art_image
);

$R1_data = array(
	array(name=>'id'),
	/*array(
		'name'=>				'ordre',
		'titre'=>				'',
		'sqlType'=>				'int',
		'sqlDefaut'=>			1,
		'nbChar'=>				4,
		'bilingue'=>			0,
		'input'=>				'',//text
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				'', //1,
		'tips'=>				'',
		'separateur'=>			'',	
	),*/
	array(
		'name'=>				'statut',
		'titre'=>				'',
		'sqlType'=>				'tinyint',
		'sqlDefaut'=>			1,
		'nbChar'=>				1,
		'bilingue'=>			0,
		'input'=>				'select',
		'valeur'=>				($_SESSION[SITE_CONFIG]['ADMIN']['type'] != '3'  ? array('0', '1') : array('0', '1', '2', '3')),
		'titrevaleur'=>			($_SESSION[SITE_CONFIG]['ADMIN']['type'] != '3'  ? array('En cours', 'A valider') :  array('En cours', 'A valider', 'Valide', 'Archive')),
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'',
		'separateur'=>			'',
	),
	array(
		'name'=>				'une',
		'titre'=>				'A la une',
		'sqlType'=>				'tinyint',
		'sqlDefaut'=>			1,
		'nbChar'=>				1,
		'bilingue'=>			0,
		'input'=>				($_SESSION[SITE_CONFIG]['ADMIN']['type'] != '3' ? '' : 'radio'),
		'valeur'=>				array('1','0'),
		'titrevaleur'=>			array('Oui','Non'),
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'Article &quot;&agrave; la une&quot;',
		'separateur'=>			'',
	),
	array(
		'name'=>				'rubrique_id',
		'titre'=>				'Rubrique',
		'sqlType'=>				'int',
		'sqlDefaut'=>			0,
		'nbChar'=>				8,
		'bilingue'=>			0,
		'input'=>				'select',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'cms_pages:id:titre_fr::type_id=21',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'Page ayant le type &quot;Module shopping&quot;',
		'separateur'=>			'',
	),
	
	array(
		'name'=>				'utilisateur_id',
		'titre'=>				'Journaliste',
		'sqlType'=>				'int',
		'sqlDefaut'=>			0,
		'nbChar'=>				8,
		'bilingue'=>			0,
		'input'=>				'select',
		'valeur'=>				($_SESSION[SITE_CONFIG]['ADMIN']['type'] != '3' && $mode == 'fiche' && $id < 1 ? array($_SESSION[SITE_CONFIG]['ADMIN']['id']) : ''),
		'titrevaleur'=>			($_SESSION[SITE_CONFIG]['ADMIN']['type'] != '3' && $mode == 'fiche' && $id < 1 ? array($_SESSION[SITE_CONFIG]['ADMIN']['prenom'].' '.$_SESSION[SITE_CONFIG]['ADMIN']['nom']) :  ''),
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				($_SESSION[SITE_CONFIG]['ADMIN']['type'] != '3' ? '1' : ''),
		'relation'=>			'',
		'inc'=>					($_SESSION[SITE_CONFIG]['ADMIN']['type'] != '3' && $mode == 'fiche' && $id < 1 ? '' : 'admin_utilisateurs:id:nom-prenom'),
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'Pour ajouter un utilisateur : <a href="../admin_utilisateurs/" target="_blank">Cliquer ici</a>'.js("$('utilisateur_id').selected.index='2'", false),
		'separateur'=>			'Article',
	),
	
	array(
		'name'=>				'datepub',
		'titre'=>				'Date publication',
		'sqlType'=>				'datetime',
		'sqlDefaut'=>			'',
		'nbChar'=>				'',
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'datetime',
		'oblige'=>				1,
		'disable'=>				1,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'Ex. : '.getDateTime(),
		'separateur'=>			'',
	),
	

	array(
		'name'=>				'titre',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			'',
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'',
		'separateur'=>			'',
	),

	array(
		'name'=>				'texte',
		'titre'=>				'Article',
		'sqlType'=>				'text',
		'sqlDefaut'=>			0,
		'nbChar'=>				'',
		'bilingue'=>			0,
		'input'=>				'textarea',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				5,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'700 signes max. Utilisation du format &quot;Titre H4&quot; pour les légendes',
		'separateur'=>			'',
	),
	array(
		'name'=>				'image',
		'titre'=>				'Image 1',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				70,
		'bilingue'=>			0,
		'input'=>				'file',
		'valeur'=>				'',
		'titrevaleur'=>		'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'img',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'Formats : jpg/gif/png',
	),
	array(
		'name'=>				'image_leg_1',
		'titre'=>				'Légende image 1',
		'sqlType'=>				'text',
		'sqlDefaut'=>			0,
		'nbChar'=>				'250',
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				'',
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
		'separateur'=>			'',
	),
);

for ($i=1; $i<=7; $i++) {

	$R1_data[] = array(
		'name'=>				'titre_'.$i,
		'titre'=>				'Titre',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			'',
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				'',
		'tips'=>				'',
		'separateur'=>			'Produit '.$i,
	);
	$R1_data[] = array(
		'name'=>				'marque_'.$i,
		'titre'=>				'Marque',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			'',
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				'',
		'tips'=>				'',
		'separateur'=>			'',
	);
	$R1_data[] = array(
		'name'=>				'prix_'.$i,
		'titre'=>				'Prix',
		'sqlType'=>				'float',
		'sqlDefaut'=>			'',
		'nbChar'=>				'8,2',
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'En &euro;',
		'separateur'=>			'',
	);
	$R1_data[] = array(
		'name'=>				'image_'.$i,
		'titre'=>				'Image',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				70,
		'bilingue'=>			0,
		'input'=>				'file',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'img',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				'',
		'tips'=>				'Formats : jpg/gif/png',
	);
}

//$C = new SQL($R1); $C->createSQL($R1_data,'1');
//$C = new SQL($R1); $C->addSQL($R1_data);





// -------------------- PRODUITS --------------------------- // 
$R2 = array(
	'table'=>					'mod_shopping_commentaires',
	'titre'=>					'Commentaire',
	'titres'=>					'',
	'genre'=>					'',
	'relation'=>				$R1['table'].':id:titre:article_id',
	'rubrelation'=>			'',
	'childRel'=>				'',
	'rubLevel'=>				'',
	'prodLevel'=>				'',
	'wherenot'=>				'',
	'postbdd'=>					'',
	'preview'=>					'',
	'ifr '=>						'',
	'boutonFiche'=>			'',
	'boutonListe'=>			'',
	'filtre'=>					array('statut'=>'todo'),
	'ordre'=>					'datepub DESC',
	'miseenavant'=>			'',
	'fixe'=>						'',
	'tips'=>				'',
	'rep'=>						$rep.'articles/',
	'sizeimg'=>					array('mini'=>'120x80', 'medium'=>'300x170', 'grand'=>'600x350')
);

$R2_data = array(
	array(name=>'id'),
	array(
		'name'=>				'statut',
		'titre'=>				'Valide',
		'sqlType'=>				'tinyint',
		'sqlDefaut'=>			1,
		'nbChar'=>				1,
		'bilingue'=>			0,
		'input'=>				'radio',
		'valeur'=>				array('0', '1'),
		'titrevaleur'=>		array('Non', 'Oui'),
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'',
		'separateur'=>			'',
	),
	
	array(
		'name'=>				'article_id',
		'titre'=>				'Article',
		'sqlType'=>				'int',
		'sqlDefaut'=>			1,
		'nbChar'=>				8,
		'bilingue'=>			0,
		'input'=>				'select',
		'valeur'=>				'',
		'titrevaleur'=>		'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			1,
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'',
		'separateur'=>			'',
	),
	
	array(
		'name'=>				'datepub',
		'titre'=>				'Date',
		'sqlType'=>				'datetime',
		'sqlDefaut'=>			'',
		'nbChar'=>				'',
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'datetime',
		'oblige'=>				1,
		'disable'=>				1,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'Ex. : '.getDateTime(),
		'separateur'=>			'',
	),
	
	array(
		'name'=>				'membre_id',
		'titre'=>				'Membre',
		'sqlType'=>				'int',
		'sqlDefaut'=>			0,
		'nbChar'=>				8,
		'bilingue'=>			0,
		'input'=>				'select',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'mod_membres:id:nom-prenom',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'Pour ajouter un membre : <a href="../mod_membres/" target="_blank">Cliquer ici</a>',
		'separateur'=>			'',
	),
	
	array(
		'name'=>				'auteur',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			'',
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'',
		'separateur'=>			'',
	),
	
	array(
		'name'=>				'email',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			'',
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>		'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'',
		'separateur'=>			'',
	),
	
	array(
		'name'=>				'titre',
		'titre'=>				'Titre',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			'',
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>		'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'',
		'separateur'=>			'',
	),
	
	array(
		'name'=>				'commentaire',
		'titre'=>				'',
		'sqlType'=>				'text',
		'sqlDefaut'=>			0,
		'nbChar'=>				'',
		'bilingue'=>			0,
		'input'=>				'textarea',
		'valeur'=>				'',
		'titrevaleur'=>		'',
		'wysiwyg'=>				'',
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				'1',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
		'separateur'=>			'',
	),

);
//$C = new SQL($R2); $C->createSQL($R2_data,'1');
//$C = new SQL($R2); $C->addSQL($R2_data);

?>