<?

// -------------------- RAPPORT TO CATEGORIES --------------------------- // 
/* 
	$CAT_PROD = array(table => 'cms_pages_relation_cms_elements');
	$CAT_PROD_data = array(
		array(name=>'id'),
		array(name=>'cat_id',sqlType=>'int',nbChar=>'8'),
		array(name=>'prod_id',sqlType=>'int',nbChar=>'8'),
		array(name=>'ordre',sqlType=>'int',nbChar=>'4'),
	);
	//$C = new SQL($CAT_PROD); $C->createSQL($CAT_PROD_data,'1'); 
	
	$CAT_REL = array(table => 'cms_pages_relation_cms_blocs');
	$CAT_REL_data = array(
		array(name=>'id'),
		array(name=>'cat_id',sqlType=>'int',nbChar=>'8'),
		array(name=>'prod_id',sqlType=>'int',nbChar=>'8'),
		array(name=>'ordre',sqlType=>'int',nbChar=>'4'),
	);
	//$C = new SQL($CAT_REL); $C->createSQL($CAT_REL_data,'1');
*/

// -------------------- PAGES --------------------------- //

$boutonListe = '';//'<table  border="0" cellspacing="0" cellpadding="0"><tr><td width="1"><img src="../images/images/button_01.png" width="15" height="18" /></td><td nowrap="nowrap" background="../images/images/button_02.png"><a href="index_tree.php" onclick="return myPop(\'index_tree3.php\',\'tree_view\',\'800\',\'600\');" class="menu">Organiser les rubriques</a></td><td width="1"><img src="../images/images/button_04.png" width="7" height="18" /></td></tr></table>';


$R0 = array(
	'table'=>					'cms_pages',
	'titre'=>					'Page du site',
	'titres'=>					'Pages du site',
	'genre'=>					'e',
	'cms'=>						1,
	'relation'=>				'', // parent:1
	'rubrelation'=>				'cms_pages:id:titre_fr:pid',
	'childRel'=>				'cms_pages:cms_pages_relation_mod_articles:mod_articles:cat_id=id:prod_id=id:titre_fr:titre_fr',
	'rubLevel'=>				'0:2',
	'prodLevel'=>				'1:2',
	'wherenot'=>				'',
	'postbdd'=>					'',
	'preview'=>					'',
	'ifr '=>					'',
	'boutonFiche'=>				'',
	'boutonListe'=>				$boutonListe,
	'filtre'=>					'',
	'ordre'=>					'',
	'miseenavant'=>				'',
	'fixe'=>					'',
	'tips'=>				'',
	'rep'=>						$rep.'pages/',
	'sizeimg'=>					array( mini=>'100x130', medium=>'170x220', grand=>'720x576', tgrand=>'814x150xXY' ),
);

$R0_data = array(
	array(name=>'id'),
	array(
		'name'=>				'ordre',
		'titre'=>				'',
		'sqlType'=>				'int',
		'sqlDefaut'=>			1,
		'nbChar'=>				4,
		'bilingue'=>			0,
		'input'=>				'', //text
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'',
		'separateur'=>			'',	
	),
	array(
		'name'=>				'actif',
		'titre'=>				'Visible',
		'sqlType'=>				'tinyint',
		'sqlDefaut'=>			1,
		'nbChar'=>				1,
		'bilingue'=>			0,
		'input'=>				'radio',
		'valeur'=>				array('1','0'),
		'titrevaleur'=>			array('Oui','Non'),
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'',
		'separateur'=>			'Comportement de la page',
	),
	
	array(
		'name'=>				'pid',
		'titre'=>				'Rubrique parente',
		'sqlType'=>				'int',
		'sqlDefaut'=>			0,
		'nbChar'=>				8,
		'bilingue'=>			0,
		'input'=>				'select',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			1,
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
		'separateur'=>			'',
	),

	array(
		'name'=>				'type_id',
		'titre'=>				'Type de page',
		'sqlType'=>				'tinyint',
		'sqlDefaut'=>			0,
		'nbChar'=>				8,
		'bilingue'=>			0,
		'input'=>				'select',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'cms_pages_types:id:titre::actif=1',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'Type de page, module dynamique spécifique',
		'separateur'=>			'',
	),
	array(
		'name'=>				'lien',
		'titre'=>				'Lien de redirection',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				250,
		'bilingue'=>			1,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'Cette rubrique peut rediriger sur ce lien (interne ou externe) si le &quot;Type de page&quot; est &quot;[Redirection] Lien&quot;',
		'separateur'=>			'',
	),
	array(
		'name'=>				'menu',
		'titre'=>				'',
		'sqlType'=>				'tinyint',
		'sqlDefaut'=>			1,
		'nbChar'=>				1,
		'bilingue'=>			0,
		'input'=>				'radio',
		'valeur'=>				array('1','0'),
		'titrevaleur'=>			array('Oui','Non'),
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'S\'affiche dans le menu',
		'separateur'=>			'',
	),
	array(
		'name'=>				'plan',
		'titre'=>				'Affichage plan du site',
		'sqlType'=>				'tinyint',
		'sqlDefaut'=>			1,
		'nbChar'=>				1,
		'bilingue'=>			0,
		'input'=>				'radio',
		'valeur'=>				array('1','0'),
		'titrevaleur'=>			array('Oui','Non'),
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
		'separateur'=>			'',
	),
	
	array(
		'name'=>				'titre',
		'titre'=>				'Titre',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			1,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'Titre court, s\'affiche dans le menu',
		'separateur'=>			'Informations sur la page',
	),
	array(
		'name'=>				'titre_page',
		'titre'=>				'Titre page',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				250,
		'bilingue'=>			1,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'Titre long, s\'affiche dans le corps de la page (Titre menu par défaut)',
		'separateur'=>			'',
	),
	
	array(
		'name'=>				'couleur',
		'titre'=>				'',
		'sqlType'=>				'tinyint',
		'sqlDefaut'=>			1,
		'nbChar'=>				1,
		'bilingue'=>			0,
		'input'=>				'select',
		'valeur'=>				array_keys($couleurs),
		'titrevaleur'=>			array_values($couleurs),
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'Couleur principale de la rubrique, uniquement rubriques racines',
		'separateur'=>			'',
	),

	array(
		'name'=>				'meta_titre',
		'titre'=>				'Titre (méta)',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			1,
		'input'=>				( SITE_REF ? 'text' : '' ),
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'Titre menu par défaut',
		'separateur'=>			'Référencement',
	),
	array(
		'name'=>				'meta_url',
		'titre'=>				'Url préfix (méta)',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			1,
		'input'=>				( SITE_REF ? 'text' : '' ),
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'Titre menu par défaut',
		'separateur'=>			'',
	),
	array(
		'name'=>				'meta_description',
		'titre'=>				'Description (méta)',
		'sqlType'=>				'text',
		'sqlDefaut'=>			'',
		'nbChar'=>				'',
		'bilingue'=>			1,
		'input'=>				( SITE_REF ? 'textarea' : '' ),
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
		'separateur'=>			'',
	),
	array(
		'name'=>				'meta_key',
		'titre'=>				'Mots-clé (méta)',
		'sqlType'=>				'text',
		'sqlDefaut'=>			'',
		'nbChar'=>				'',
		'bilingue'=>			1,
		'input'=>				( SITE_REF ? 'textarea' : '' ),
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
		'separateur'=>			'',
	),
	
	/*
	array(
		'name'=>				'bloc_gauche_ids',
		'titre'=>				'Bloc(s) associé(s) à gauche',
		'sqlType'=>				'',
		'sqlDefaut'=>			'',
		'nbChar'=>				'',
		'bilingue'=>			0,
		'input'=>				'multiselect',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'relation',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'cms_pages_relation_cms_blocs:cms_blocs:cat_id=id:prod_id=id:titre',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
		'separateur'=>			'Champs optionnels de la fiche rubrique',
	),
	array(
		'name'=>				'bloc_droit_ids',
		'titre'=>				'Bloc(s) associé(s) à droite',
		'sqlType'=>				'',
		'sqlDefaut'=>			'',
		'nbChar'=>				'',
		'bilingue'=>			0,
		'input'=>				'multiselect',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'relation',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'pages_relation_bloc_droite:blocs_de_colonne:cat_id=id:prod_id=id:titre',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
		'separateur'=>			'',
	),
	array(
		'name'=>				'visuel',
		'titre'=>				'Visuel principal',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				70,
		'bilingue'=>			0,
		'input'=>				'file',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'img',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'Formats : jpg/gif/png',
	),
	*/
);
//$C = new SQL($R0); $C->createSQL($R0_data,'1');
//$C = new SQL($R0); $C->addSQL($R0_data,'1');





// -------------------- PRODUITS 1 --------------------------- // 
$RX = array(
	'table'=>					'cms_pages_elements',
	'titre'=>					'Element de page',
	'titres'=>					'Elements de page',
	'genre'=>					'e',
	'relation'=>				$R0['table'].':id:titre_fr:pid',
	'rubrelation'=>				'',
	'childRel'=>				'',
	'rubLevel'=>				'',
	'prodLevel'=>				'',
	'wherenot'=>				'',
	'postbdd'=>					'',
	'preview'=>					'',
	'ifr '=>					'',
	'boutonFiche'=>				'',
	'boutonListe'=>				'',
	'filtre'=>					'',
	'ordre'=>					'',
	'miseenavant'=>				'',
	'fixe'=>					0,
	'tips'=>				'',
	'rep'=>						'',
	'sizeimg'=>					'',		
);
$RX_data = array(
	array(name=>'id'),
	array(
		'name'=>				'ordre',
		'titre'=>				'',
		'sqlType'=>				'int',
		'sqlDefaut'=>			1,
		'nbChar'=>				4,
		'bilingue'=>			0,
		'input'=>				'', //text
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'',
		'separateur'=>			'',	
	),
	array(
		'name'=>				'actif',
		'titre'=>				'Visible',
		'sqlType'=>				'tinyint',
		'sqlDefaut'=>			1,
		'nbChar'=>				1,
		'bilingue'=>			0,
		'input'=>				'radio',
		'valeur'=>				array('1','0'),
		'titrevaleur'=>			array('Oui','Non'),
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'',
		'separateur'=>			'Comportement de la page',
	),
	array(
		'name'=>				'pid',
		'titre'=>				'Page parente',
		'sqlType'=>				'int',
		'sqlDefaut'=>			1,
		'nbChar'=>				8,
		'bilingue'=>			0,
		'input'=>				'select',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			1,
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				''
	),
	array(
		'name'=>				'type_id',
		'titre'=>				'Type d\'élément',
		'sqlType'=>				'tinyint',
		'sqlDefaut'=>			0,
		'nbChar'=>				8,
		'bilingue'=>			0,
		'input'=>				'select',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'cms_elements_types:id:titre',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'',
		'separateur'=>			'',
	),
	array(
		'name'=>				'langue',
		'titre'=>				'Langue',
		'sqlType'=>				'char',
		'sqlDefaut'=>			'fr',
		'nbChar'=>				2,
		'bilingue'=>			0,
		'input'=>				'select',
		'valeur'=>				array_values($langues),
		'titrevaleur'=>			array_values($langues),
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'',
		'separateur'=>			'',
	),
	array(
		'name'=>				'valeurs',
		'titre'=>				'',
		'sqlType'=>				'text',
		'sqlDefaut'=>			'',
		'nbChar'=>				'',
		'bilingue'=>			0,
		'input'=>				'textarea',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'Array PHP sérialisé des paramètres',
		'separateur'=>			'',
	),
	
	array(
		'name'=>				'motcle',
		'titre'=>				'',
		'sqlType'=>				'text',
		'sqlDefaut'=>			'',
		'nbChar'=>				'',
		'bilingue'=>			0,
		'input'=>				'textarea',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'Array PHP sérialisé des paramètres',
		'separateur'=>			'',
	)
);
//$C = new SQL($RX); $C->createSQL($RX_data,'1');
//$C = new SQL($RX); $C->addSQL($RX_data);








//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////









// -------------------- RELATION RUBRIQUE TO PRODUITS --------------------------- // 
$CAT_PROD = array(table => 'cms_pages_relation_mod_articles');
$CAT_PROD_data = array(
	array(name=>'id'),
	array(name=>'cat_id',sqlType=>'int',nbChar=>'8'),
	array(name=>'prod_id',sqlType=>'int',nbChar=>'8'),
	array(name=>'ordre',sqlType=>'int',nbChar=>'4'),
);
//$C = new SQL($CAT_PROD); $C->createSQL($CAT_PROD_data,'1');


$mode = gpc('mode');
if (($mode == 'fiche' || $mode == 'bdd') && gpc('id') > 0) {
	$id = gpc('id');
	$A =& new Q("SELECT cat_id FROM cms_pages_relation_mod_articles WHERE prod_id='".$id."' LIMIT 1");
	$rub_id = intval($A->V[0]['cat_id']);
	if ($rub_id < 1) $boutonFiche = '<strong>ATTENTION : vous n\'avez pas défini de rubrique(s) pour votre article</strong>';
	else {
		$boutonFiche = '<table  border="0" cellspacing="0" cellpadding="0"><tr><td width="1"><img src="../images/images/button_01.png" width="15" height="18" /></td><td nowrap="nowrap" background="../images/images/button_02.png"><a href="'.$WWW.'index_article.php?article_id='.$id.'" class="menu">Exporter l\'article au format word</a></td><td width="1"><img src="../images/images/button_04.png" width="7" height="18" /></td></tr></table>';
		
		$previewf = $WWW.'article-r'.$rub_id.'-a'.$id.'.html';
	}
}


// -------------------- PRODUITS --------------------------- // 
$R1 = array(
	'table'=>					'mod_articles',
	'titre'=>					'Article',
	'titres'=>					'',
	'genre'=>					'',
	'relation'=>				'parent:1',
	'rubrelation'=>				'',
	'childRel'=>				'1',
	'rubLevel'=>				'',
	'prodLevel'=>				'1:2',
	'wherenot'=>				'',
	'postbdd'=>					'',
	'preview'=>					'',
	'previewf'=>				$previewf,
	'ifr '=>					'',
	'boutonFiche'=>				$boutonFiche,
	'boutonListe'=>				'',
	'filtre'=>					array('statut'=>'todo', 'utilisateur_id'=>($_SESSION[SITE_CONFIG]['ADMIN']['type'] != '3' ? $_SESSION[SITE_CONFIG]['ADMIN']['id'] : 'todo')),
	'ordre'=>					'datepub DESC',
	'miseenavant'=>				'',
	'fixe'=>					'',
	'tips'=>				'<br />Vous pouvez prévisualiser votre article dans le site avant que celui si ne soit publié (statut = Valide)',
	'rep'=>						$rep.'articles/',
	'sizeimg'=>					$arr_art_image
);

$R1_data = array(
	array(name=>'id'),
	/*array(
		'name'=>				'ordre',
		'titre'=>				'',
		'sqlType'=>				'int',
		'sqlDefaut'=>			1,
		'nbChar'=>				4,
		'bilingue'=>			0,
		'input'=>				'',//text
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				'', //1,
		'tips'=>				'',
		'separateur'=>			'',	
	),*/
	array(
		'name'=>				'statut',
		'titre'=>				'',
		'sqlType'=>				'tinyint',
		'sqlDefaut'=>			1,
		'nbChar'=>				1,
		'bilingue'=>			0,
		'input'=>				'select',
		'valeur'=>				($_SESSION[SITE_CONFIG]['ADMIN']['type'] != '3'  ? array('0', '1') : array('0', '1', '2', '3')),
		'titrevaleur'=>			($_SESSION[SITE_CONFIG]['ADMIN']['type'] != '3'  ? array('En cours', 'A valider') :  array('En cours', 'A valider', 'Valide', 'Archive')),
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'',
		'separateur'=>			'',
	),
	array(
		'name'=>				'une',
		'titre'=>				'A la une',
		'sqlType'=>				'tinyint',
		'sqlDefaut'=>			1,
		'nbChar'=>				1,
		'bilingue'=>			0,
		'input'=>				($_SESSION[SITE_CONFIG]['ADMIN']['type'] != '3' ? '' : 'radio'),
		'valeur'=>				array('1','0'),
		'titrevaleur'=>			array('Oui','Non'),
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'Article &quot;&agrave; la une&quot;',
		'separateur'=>			'',
	),
	array(
		'name'=>				'utilisateur_id',
		'titre'=>				'Journaliste',
		'sqlType'=>				'int',
		'sqlDefaut'=>			0,
		'nbChar'=>				8,
		'bilingue'=>			0,
		'input'=>				'select',
		'valeur'=>				($_SESSION[SITE_CONFIG]['ADMIN']['type'] != '3' && $mode == 'fiche' && $id < 1 ? array($_SESSION[SITE_CONFIG]['ADMIN']['id']) : ''),
		'titrevaleur'=>			($_SESSION[SITE_CONFIG]['ADMIN']['type'] != '3' && $mode == 'fiche' && $id < 1 ? array($_SESSION[SITE_CONFIG]['ADMIN']['prenom'].' '.$_SESSION[SITE_CONFIG]['ADMIN']['nom']) :  ''),
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				($_SESSION[SITE_CONFIG]['ADMIN']['type'] != '3' ? '1' : ''),
		'relation'=>			'',
		'inc'=>					($_SESSION[SITE_CONFIG]['ADMIN']['type'] != '3' && $mode == 'fiche' && $id < 1 ? '' : 'admin_utilisateurs:id:nom-prenom'),
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'Pour ajouter un utilisateur : <a href="../admin_utilisateurs/" target="_blank">Cliquer ici</a>'.js("$('utilisateur_id').selected.index='2'", false),
		'separateur'=>			'Article',
	),
	
	array(
		'name'=>				'datepub',
		'titre'=>				'Date publication',
		'sqlType'=>				'datetime',
		'sqlDefaut'=>			'',
		'nbChar'=>				'',
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'datetime',
		'oblige'=>				1,
		'disable'=>				'',
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'Ex. : '.getDateTime(),
		'separateur'=>			'',
	),
	

	array(
		'name'=>				'titre',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			'',
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'',
		'separateur'=>			'',
	),
	array(
		'name'=>				'chapeau',
		'titre'=>				'',
		'sqlType'=>				'text',
		'sqlDefaut'=>			0,
		'nbChar'=>				'',
		'bilingue'=>			0,
		'input'=>				'textarea',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				'2',
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'400 signes, texte qui apparait en mode &quot;liste&quot;.<br />
								Pas la peine de mettre en gras, le style est automatique',
		'separateur'=>			'',
	),
	array(
		'name'=>				'texte_1',
		'titre'=>				'Article',
		'sqlType'=>				'text',
		'sqlDefaut'=>			0,
		'nbChar'=>				'',
		'bilingue'=>			0,
		'input'=>				'textarea',
		'valeur'=>				'',
		'titrevaleur'=>		'',
		'wysiwyg'=>				5,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'3000 signes max. Utilisation du format &quot;Titre H2&quot; pour les titres dans le texte, &quot;Titre H4&quot; pour les légendes',
		'separateur'=>			'',
	),
	array(
		'name'=>				'titre_inter',
		'titre'=>				'Inter-titre',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				250,
		'bilingue'=>			'',
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>		'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				'',
		'tips'=>				'',
		'separateur'=>			'',
	),
	/*array(
		'name'=>				'texte_2',
		'titre'=>				'Texte 2',
		'sqlType'=>				'text',
		'sqlDefaut'=>			0,
		'nbChar'=>				'',
		'bilingue'=>			0,
		'input'=>				'', //textarea
		'valeur'=>				'',
		'titrevaleur'=>		'',
		'wysiwyg'=>				5,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'1500 signes',
		'separateur'=>			'',
	),*/
	
	array(
		'name'=>				'image_1',
		'titre'=>				'Image 1',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				70,
		'bilingue'=>			0,
		'input'=>				'file',
		'valeur'=>				'',
		'titrevaleur'=>		'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'img',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'Formats : jpg/gif/png',
	),
	array(
		'name'=>				'image_leg_1',
		'titre'=>				'Légende image 1',
		'sqlType'=>				'text',
		'sqlDefaut'=>			0,
		'nbChar'=>				'250',
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				'',
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
		'separateur'=>			'',
	),
	
	
	array(
		'name'=>				'type',
		'titre'=>				'Type d\'article',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				'2',
		'bilingue'=>			0,
		'input'=>				'select',
		'valeur'=>				array('S','F','M','L','J','T','O'),
		'titrevaleur'=>			array('Standard','Film','Musique','Livre','Jeux','Théâtre','Opéra'),
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'S',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=> 				1,
		'action'=>				'',
		'index'=>				'',
		'tips'=>				'<strong>Standard :</strong> Laisser les champs vides<br />
								<strong>Film :</strong> R&eacute;alisateur, avec, titre du film (Genre et nationalité)<br />
								<strong>Musique :</strong> Artiste, label, titre de l\'album<br />
								<strong>Livre :</strong> Aauteur, &eacute;diteur, titre du livre<br />
								<strong>Jeux :</strong> R&eacute;alisateur, &eacute;diteur, titre du jeux<br />
								<strong>Th&eacute;&acirc;tre :</strong> Metteur en sc&egrave;ne (MES), avec, titre de la pi&egrave;ce<br />
								<strong>Op&eacute;ra :</strong> Compositeur, avec, titre de la pi&egrave;ce',
		'separateur'=>			'...Suivant le type de l\'article',
	),
	
	array(
		'name'=>				'prod_auteur',
		'titre'=>				'Artiste/Auteur/Réalisateur/MES/...',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				250,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
		'separateur'=>			'',
	),
	array(
		'name'=>				'prod_editeur',
		'titre'=>				'Label/Editeur/Avec/...',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				250,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
		'separateur'=>			'',
	),
	array(
		'name'=>				'prod_titre',
		'titre'=>				'Album/Livre/Film/...',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				250,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
		'separateur'=>			'',
	),
	
	array(
		'name'=>				'genre',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				100,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
		'separateur'=>			'',
	),
	array(
		'name'=>				'nationalite',
		'titre'=>				'Nationalité',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				100,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
		'separateur'=>			'',
	),

	array(
		'name'=>				'datedeb',
		'titre'=>				'Date (début)',
		'sqlType'=>				'datetime',
		'sqlDefaut'=>			'',
		'nbChar'=>				'',
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'datetime',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				'',
		'tips'=>				'Ex. : '.getDateTime(),
		'separateur'=>			'Informations supplémentaires',
	),
	array(
		'name'=>				'datefin',
		'titre'=>				'Date fin',
		'sqlType'=>				'datetime',
		'sqlDefaut'=>			'',
		'nbChar'=>				'',
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'datetime',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				'',
		'tips'=>				'Ex. : '.getDateTime(),
		'separateur'=>			'',
	),
	
	array(
		'name'=>				'note',
		'titre'=>				'Note rédaction',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				'5',
		'bilingue'=>			0,
		'input'=>				'radio',
		'valeur'=>				array('Non','0', '1', '2', '3', '4', '5'),
		'titrevaleur'=>			array('Non','0', '1', '2', '3', '4', '5'),
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				'',
		'tips'=>				'',
		'separateur'=>			'',
	),
	array(
		'name'=>				'prix',
		'titre'=>				'',
		'sqlType'=>				'float',
		'sqlDefaut'=>			'',
		'nbChar'=>				'8,2',
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'En &euro;',
		'separateur'=>			'',
	),
	array(
		'name'=>				'virgin_id',
		'titre'=>				'N° ID virgin',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				250,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'Permet de faire un lien vers le produit sur le site de <a href=http://www.vm-wl.com/Default.aspx?RefererId=87&BannerId=1&FicheArtiste=217905 target=_blank>virgin</a><br />
								Exemple : &quot;217905&quot;. <a href=http://www.vm-wl.com/Default.aspx?RefererId=87&BannerId=1&FicheArtiste=217905 target=_blank>http://www.vm-wl.com/Default.aspx?RefererId=87&BannerId=1&FicheArtiste=<strong>217905</strong></a>',
		'separateur'=>			'',
	),
	
	array(
		'name'=>				'contact',
		'titre'=>				'Infos supp.',
		'sqlType'=>				'text',
		'sqlDefaut'=>			0,
		'nbChar'=>				'',
		'bilingue'=>			0,
		'input'=>				'textarea',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				'1',
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'Email/Site/Adresse/...',
		'separateur'=>			'',
	),
	
	array(
		'name'=>				'ville_id',
		'titre'=>				'Ville',
		'sqlType'=>				'int',
		'sqlDefaut'=>			0,
		'nbChar'=>				8,
		'bilingue'=>			0,
		'input'=>				'select',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'dat_villes:id:ville-code_ville',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'Pour le module &quot;O&uacute; Sortir&quot;',
		'separateur'=>			'',
	),
	
	/*
	array(
		'name'=>				'agenda',
		'titre'=>				'',
		'sqlType'=>				'text',
		'sqlDefaut'=>			0,
		'nbChar'=>				'',
		'bilingue'=>			0,
		'input'=>				'textarea',
		'valeur'=>				'',
		'titrevaleur'=>		'',
		'wysiwyg'=>				5,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'Email/Site',
		'separateur'=>			'',
	),
	array(
		'name'=>				'Lieu_id',
		'titre'=>				'Lieu (répertoire)',
		'sqlType'=>				'int',
		'sqlDefaut'=>			0,
		'nbChar'=>				8,
		'bilingue'=>			0,
		'input'=>				'select',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'mod_lieux:id:titre',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'Pour ajouter un lieu : <a href="../mod_lieux/" target="_blank">Cliquer ici</a>',
		'separateur'=>			'',
	),
	*/
	
	
	
	array(
		'name'=>				'image_2',
		'titre'=>				'Image 2',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				70,
		'bilingue'=>			0,
		'input'=>				'file',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'img',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				'',
		'tips'=>				'Formats : jpg/gif/png',
		'separateur'=>			'Visuel supplémentaires',
	),
	array(
		'name'=>				'image_leg_2',
		'titre'=>				'Légende image 2',
		'sqlType'=>				'text',
		'sqlDefaut'=>			0,
		'nbChar'=>				'250',
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				'',
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
		'separateur'=>			'',
	),
	
	array(
		'name'=>				'image_3',
		'titre'=>				'Image 3',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				70,
		'bilingue'=>			0,
		'input'=>				'file',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'img',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				'',
		'tips'=>				'Formats : jpg/gif/png',
	),
	array(
		'name'=>				'image_leg_3',
		'titre'=>				'Légende image 3',
		'sqlType'=>				'text',
		'sqlDefaut'=>			0,
		'nbChar'=>				'250',
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				'',
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
		'separateur'=>			'',
	),
	
	array(
		'name'=>				'image_4',
		'titre'=>				'Image 4',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				70,
		'bilingue'=>			0,
		'input'=>				'file',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'img',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				'',
		'tips'=>				'Formats : jpg/gif/png',
	),
	array(
		'name'=>				'image_leg_4',
		'titre'=>				'Légende image 4',
		'sqlType'=>				'text',
		'sqlDefaut'=>			0,
		'nbChar'=>				'250',
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				'',
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
		'separateur'=>			'',
	),
	
	array(
		'name'=>				'image_5',
		'titre'=>				'Image 5',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				70,
		'bilingue'=>			0,
		'input'=>				'file',
		'valeur'=>				'',
		'titrevaleur'=>		'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'img',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				'',
		'tips'=>				'Formats : jpg/gif/png',
	),
	array(
		'name'=>				'image_leg_5',
		'titre'=>				'Légende image 5',
		'sqlType'=>				'text',
		'sqlDefaut'=>			0,
		'nbChar'=>				'250',
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>		'',
		'wysiwyg'=>				'',
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
		'separateur'=>			'',
	),

);
//$C = new SQL($R1); $C->createSQL($R1_data,'1');
//$C = new SQL($R1); $C->addSQL($R1_data);





// -------------------- PRODUITS --------------------------- // 
$R2 = array(
	'table'=>					'mod_articles_commentaires',
	'titre'=>					'Commentaire',
	'titres'=>					'',
	'genre'=>					'',
	'relation'=>				$R1['table'].':id:titre:article_id',
	'rubrelation'=>			'',
	'childRel'=>				'',
	'rubLevel'=>				'',
	'prodLevel'=>				'',
	'wherenot'=>				'',
	'postbdd'=>					'',
	'preview'=>					'',
	'ifr '=>						'',
	'boutonFiche'=>			'',
	'boutonListe'=>			'',
	'filtre'=>					array('statut'=>'todo'),
	'ordre'=>					'datepub DESC',
	'miseenavant'=>			'',
	'fixe'=>						'',
	'tips'=>				'',
	'rep'=>						$rep.'articles/',
	'sizeimg'=>					array('mini'=>'120x80', 'medium'=>'300x170', 'grand'=>'600x350')
);

$R2_data = array(
	array(name=>'id'),
	array(
		'name'=>				'statut',
		'titre'=>				'Valide',
		'sqlType'=>				'tinyint',
		'sqlDefaut'=>			1,
		'nbChar'=>				1,
		'bilingue'=>			0,
		'input'=>				'radio',
		'valeur'=>				array('0', '1'),
		'titrevaleur'=>		array('Non', 'Oui'),
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'',
		'separateur'=>			'',
	),
	
	array(
		'name'=>				'article_id',
		'titre'=>				'Article',
		'sqlType'=>				'int',
		'sqlDefaut'=>			1,
		'nbChar'=>				8,
		'bilingue'=>			0,
		'input'=>				'select',
		'valeur'=>				'',
		'titrevaleur'=>		'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			1,
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'',
		'separateur'=>			'',
	),
	
	array(
		'name'=>				'datepub',
		'titre'=>				'Date',
		'sqlType'=>				'datetime',
		'sqlDefaut'=>			'',
		'nbChar'=>				'',
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'datetime',
		'oblige'=>				1,
		'disable'=>				1,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'Ex. : '.getDateTime(),
		'separateur'=>			'',
	),
	
	array(
		'name'=>				'membre_id',
		'titre'=>				'Membre',
		'sqlType'=>				'int',
		'sqlDefaut'=>			0,
		'nbChar'=>				8,
		'bilingue'=>			0,
		'input'=>				'select',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'mod_membres:id:nom-prenom',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'Pour ajouter un membre : <a href="../mod_membres/" target="_blank">Cliquer ici</a>',
		'separateur'=>			'',
	),
	
	array(
		'name'=>				'auteur',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			'',
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>		'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'',
		'separateur'=>			'',
	),
	
	array(
		'name'=>				'email',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			'',
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>		'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'',
		'separateur'=>			'',
	),
	
	array(
		'name'=>				'titre',
		'titre'=>				'Titre',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			'',
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>		'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'',
		'separateur'=>			'',
	),
	
	array(
		'name'=>				'commentaire',
		'titre'=>				'',
		'sqlType'=>				'text',
		'sqlDefaut'=>			0,
		'nbChar'=>				'',
		'bilingue'=>			0,
		'input'=>				'textarea',
		'valeur'=>				'',
		'titrevaleur'=>		'',
		'wysiwyg'=>				'',
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				'1',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
		'separateur'=>			'',
	),

);
//$C = new SQL($R2); $C->createSQL($R2_data,'1');
//$C = new SQL($R2); $C->addSQL($R2_data);

?>