<?

// -------------------- RAPPORT TO CATEGORIES --------------------------- // 
/* 
	$CAT_PROD = array(table => 'cms_pages_relation_cms_elements');
$CAT_PROD_data = array(
	array(name=>'id'),
	array(name=>'cat_id',sqlType=>'int',nbChar=>'8'),
	array(name=>'prod_id',sqlType=>'int',nbChar=>'8'),
	array(name=>'ordre',sqlType=>'int',nbChar=>'4'),
);
	//$C = new SQL($CAT_PROD); $C->createSQL($CAT_PROD_data,'1'); 

	$CAT_REL = array(table => 'cms_pages_relation_bloc_gauche');
	$CAT_REL_data = array(
		array(name=>'id'),
		array(name=>'cat_id',sqlType=>'int',nbChar=>'8'),
		array(name=>'prod_id',sqlType=>'int',nbChar=>'8'),
		array(name=>'ordre',sqlType=>'int',nbChar=>'4'),
	);
	//$C = new SQL($CAT_REL); $C->createSQL($CAT_REL_data,'1');
	
	$CAT_REL = array(table => 'cms_pages_relation_bloc_droite');
$CAT_REL_data = array(
	array(name=>'id'),
	array(name=>'cat_id',sqlType=>'int',nbChar=>'8'),
	array(name=>'prod_id',sqlType=>'int',nbChar=>'8'),
	array(name=>'ordre',sqlType=>'int',nbChar=>'4'),
);
//$C = new SQL($CAT_REL); $C->createSQL($CAT_REL_data,'1');
*/

// -------------------- PAGES --------------------------- //

$R0 = array(
	'table'=>					'cms_pages',
	'titre'=>					'Page du site',
	'titres'=>					'Pages du site',
	'genre'=>					'e',
	'cms'=>						1,
	'relation'=>				'', // parent:1
	'rubrelation'=>				'cms_pages:id:titre_fr:pid',
	'childRel'=>				'', // cms_pages:cms_pages_relation_cms_elements:cms_elements:cat_id=id:prod_id=id:titre_fr:titre_fr
	'rubLevel'=>				'0:2',
	'prodLevel'=>				'', // 0:2
	'wherenot'=>				'',
	'postbdd'=>					'',
	'preview'=>					'',
	'ifr '=>					'',
	'boutonFiche'=>				'',
	'boutonListe'=>				'',
	'filtre'=>					'',
	'ordre'=>					'',
	'miseenavant'=>				'',
	'fixe'=>					'',
	'tips '=>					'',
	'rep'=>						$rep.'pages/',
	'sizeimg'=>					array( mini=>'100x130', medium=>'170x220', grand=>'720x576', tgrand=>'814x150xXY' ),
);

$R0_data = array(
	array(name=>'id'),
	array(
		'name'=>				'ordre',
		'titre'=>				'',
		'sqlType'=>				'int',
		'sqlDefaut'=>			1,
		'nbChar'=>				4,
		'bilingue'=>			0,
		'input'=>				'', //text
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'',
		'separateur'=>			'',	
	),
	array(
		'name'=>				'actif',
		'titre'=>				'Visible',
		'sqlType'=>				'tinyint',
		'sqlDefaut'=>			1,
		'nbChar'=>				1,
		'bilingue'=>			0,
		'input'=>				'radio',
		'valeur'=>				array('1','0'),
		'titrevaleur'=>			array('Oui','Non'),
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'',
		'separateur'=>			'Comportement de la page',
	),

	array(
		'name'=>				'pid',
		'titre'=>				'Rubrique parente',
		'sqlType'=>				'int',
		'sqlDefaut'=>			0,
		'nbChar'=>				8,
		'bilingue'=>			0,
		'input'=>				'select',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			1,
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
		'separateur'=>			'',
	),

	array(
		'name'=>				'type_id',
		'titre'=>				'Type de page',
		'sqlType'=>				'tinyint',
		'sqlDefaut'=>			0,
		'nbChar'=>				8,
		'bilingue'=>			0,
		'input'=>				'select',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'cms_pages_types:id:titre::actif=1',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'Type de page, module dynamique spécifique',
		'separateur'=>			'',
	),
	/*array(
		'name'=>				'lien',
		'titre'=>				'Lien de redirection',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				250,
		'bilingue'=>			1,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'Cette rubrique peut rediriger sur ce lien (interne ou externe) si le &quot;Type de page&quot; est &quot;[Redirection] Lien&quot;',
		'separateur'=>			'',
	),*/
	array(
		'name'=>				'menu',
		'titre'=>				'',
		'sqlType'=>				'tinyint',
		'sqlDefaut'=>			1,
		'nbChar'=>				1,
		'bilingue'=>			0,
		'input'=>				'radio',
		'valeur'=>				array('1','0'),
		'titrevaleur'=>			array('Oui','Non'),
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>					'S\'affiche dans le menu',
		'separateur'=>			'',
	),
	/*array(
		'name'=>				'plan',
		'titre'=>				'Affichage plan du site',
		'sqlType'=>				'tinyint',
		'sqlDefaut'=>			1,
		'nbChar'=>				1,
		'bilingue'=>			0,
		'input'=>				'radio',
		'valeur'=>				array('1','0'),
		'titrevaleur'=>			array('Oui','Non'),
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
		'separateur'=>			'',
	),*/
	
	array(
		'name'=>				'titre',
		'titre'=>				'Titre',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			1,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'<strong>Titre court</strong>, s\'affiche dans le menu',
		'separateur'=>			'Informations sur la page',
	),
	/*array(
		'name'=>				'titre_page',
		'titre'=>				'Titre page',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				250,
		'bilingue'=>			1,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'S\'affiche dans le corps de la page (Titre par défaut)',
		'separateur'=>			'',
	),*/
	
	array(
		'name'=>				'meta_titre',
		'titre'=>				'Titre (méta)',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			1,
		'input'=>				( SITE_REF ? 'text' : '' ),
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'Titre par défaut',
		'separateur'=>			'Référencement',
	),
	/*array(
		'name'=>				'meta_url',
		'titre'=>				'Url préfix (méta)',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			1,
		'input'=>				( SITE_REF ? 'text' : '' ),
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>					'Titre par défaut',
		'separateur'=>			'',
	),*/
	array(
		'name'=>				'meta_description',
		'titre'=>				'Description (méta)',
		'sqlType'=>				'text',
		'sqlDefaut'=>			'',
		'nbChar'=>				'',
		'bilingue'=>			1,
		'input'=>				( SITE_REF ? 'textarea' : '' ),
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
		'separateur'=>			'',
	),
	array(
		'name'=>				'meta_key',
		'titre'=>				'Mots-clé (méta)',
		'sqlType'=>				'text',
		'sqlDefaut'=>			'',
		'nbChar'=>				'',
		'bilingue'=>			1,
		'input'=>				( SITE_REF ? 'textarea' : '' ),
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
		'separateur'=>			'',
	),
	

	/*
	array(
		'name'=>				'bloc_gauche_ids',
		'titre'=>				'Bloc(s) associé(s) à gauche',
		'sqlType'=>				'',
		'sqlDefaut'=>			'',
		'nbChar'=>				'',
		'bilingue'=>			0,
		'input'=>				'multiselect',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'relation',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'cms_pages_relation_bloc_gauche:cms_blocs:cat_id=id:prod_id=id:titre',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
		'separateur'=>			'Champs optionnels de la fiche rubrique',
	),
	
	array(
		'name'=>				'bloc_droit_ids',
		'titre'=>				'Bloc(s) associé(s) à droite',
		'sqlType'=>				'',
		'sqlDefaut'=>			'',
		'nbChar'=>				'',
		'bilingue'=>			0,
		'input'=>				'multiselect',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'relation',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'cms_pages_relation_bloc_droite:cms_blocs:cat_id=id:prod_id=id:titre',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
		'separateur'=>			'',
	),

	
	array(
		'name'=>				'visuel',
		'titre'=>				'Visuel principal',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				70,
		'bilingue'=>			0,
		'input'=>				'file',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'img',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'Formats : jpg/gif/png',
	),
	
	*/
);
//$C = new SQL($R0); $C->createSQL($R0_data,'1');
//$C = new SQL($R0); $C->addSQL($R0_data,'1');





// -------------------- PRODUITS 1 --------------------------- // 
$RX = array(
	'table'=>					'cms_pages_elements',
	'titre'=>					'Element de page',
	'titres'=>					'Elements de page',
	'genre'=>					'e',
	'relation'=>				$R0['table'].':id:titre_fr:pid',
	'rubrelation'=>				'',
	'childRel'=>				'',
	'rubLevel'=>				'',
	'prodLevel'=>				'',
	'wherenot'=>				'',
	'postbdd'=>					'',
	'preview'=>					'',
	'ifr '=>					'',
	'boutonFiche'=>				'',
	'boutonListe'=>				'',
	'filtre'=>					'',
	'ordre'=>					'',
	'miseenavant'=>				'',
	'fixe'=>					0,
	'tips '=>					'',
	'rep'=>						'',
	'sizeimg'=>					'',		
);
$RX_data = array(
	array(name=>'id'),
	array(
		'name'=>				'ordre',
		'titre'=>				'',
		'sqlType'=>				'int',
		'sqlDefaut'=>			1,
		'nbChar'=>				4,
		'bilingue'=>			0,
		'input'=>				'', //text
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'',
		'separateur'=>			'',	
	),
	array(
		'name'=>				'actif',
		'titre'=>				'Visible',
		'sqlType'=>				'tinyint',
		'sqlDefaut'=>			1,
		'nbChar'=>				1,
		'bilingue'=>			0,
		'input'=>				'radio',
		'valeur'=>				array('1','0'),
		'titrevaleur'=>			array('Oui','Non'),
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'',
		'separateur'=>			'Comportement de la page',
	),
	array(
		'name'=>				'pid',
		'titre'=>				'Page parente',
		'sqlType'=>				'int',
		'sqlDefaut'=>			1,
		'nbChar'=>				8,
		'bilingue'=>			0,
		'input'=>				'select',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			1,
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				''
	),
	array(
		'name'=>				'type_id',
		'titre'=>				'Type d\'élément',
		'sqlType'=>				'tinyint',
		'sqlDefaut'=>			0,
		'nbChar'=>				8,
		'bilingue'=>			0,
		'input'=>				'select',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'cms_elements_types:id:titre',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'',
		'separateur'=>			'',
	),
	array(
		'name'=>				'langue',
		'titre'=>				'Langue',
		'sqlType'=>				'char',
		'sqlDefaut'=>			'fr',
		'nbChar'=>				2,
		'bilingue'=>			0,
		'input'=>				'select',
		'valeur'=>				array_values($langues),
		'titrevaleur'=>			array_values($langues),
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'',
		'separateur'=>			'',
	),
	array(
		'name'=>				'valeurs',
		'titre'=>				'',
		'sqlType'=>				'text',
		'sqlDefaut'=>			'',
		'nbChar'=>				'',
		'bilingue'=>			0,
		'input'=>				'textarea',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'Array PHP sérialisé des paramètres',
		'separateur'=>			'',
	),
	array(
		'name'=>				'motcle',
		'titre'=>				'',
		'sqlType'=>				'text',
		'sqlDefaut'=>			'',
		'nbChar'=>				'',
		'bilingue'=>			0,
		'input'=>				'textarea',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'Indexation pour la recherche sur le champs',
		'separateur'=>			'',
	)
);
//$C = new SQL($RX); $C->createSQL($RX_data,'1');
//$C = new SQL($RX); $C->addSQL($RX_data);

?>