<?
$boutonListe = '';//<table  border="0" cellspacing="0" cellpadding="0"><tr><td width="1"><img src="../images/images/button_01.png" width="15" height="18" /></td><td nowrap="nowrap" background="../images/images/button_02.png"><a href="javascript:void(0);" onclick="window.open(\'../mod_clients/commandes_purge.php\',\'\',\'toolbar=yes,location=yes,status=yes,menubar=yes,scrollbars=yes,resizable=yes,width=600,height=600\');" class="menu">Purger les commandes temporaires</a></td><td width="1"><img src="../images/images/button_04.png" width="7" height="18" /></td></tr></table>';

$id = gpc('id');
if ($id > 0) {
	$A = new SQL('mod_commandes');
	$A->LireSql(array('*')," id='$id' LIMIT 1 ");
	$mailok = Aff($A->V[0]['mailok']);

	$boutonFiche = '<table  border="0" cellspacing="0" cellpadding="0">
	<tr>
	<td width="1">
	<table  border="0" cellspacing="0" cellpadding="0"><tr><td width="1"><img src="../images/images/button_01.png" width="15" height="18" /></td><td nowrap="nowrap" background="../images/images/button_02.png"><a href="javascript:void(0);" onclick="window.open(\'../mod_commandes/commande_impression.php?commande_id='.$id.'\',\'\',\'toolbar=yes,location=yes,status=yes,menubar=yes,scrollbars=yes,resizable=yes,width=600,height=600\');" class="menu">D&eacute;tail de la commande (Imprimer)</a></td><td width="1"><img src="../images/images/button_04.png" width="7" height="18" /></td></tr></table>
	</td><td>&nbsp;</td><td>
		<table  border="0" cellspacing="0" cellpadding="0">
		<tr>
		<td width="1"><img src="../images/images/button_01.png" width="15" height="18" /></td>
		<td nowrap="nowrap" background="../images/images/button_02.png">';
	if ($mailok < 1) {
		$boutonFiche .= '<a href="javascript:void(0);" onClick="window.open(\'../mod_commandes/send_mail.php?id='.$id.'\',\'\',\'width=250,height=100\');" class="menu">Envoyer e-mail validation commande</a>';
	}
	else  {
		$boutonFiche .= '<a href="javascript:void(0);" onClick="window.open(\'../mod_commandes/send_mail.php?id='.$id.'&mailok=1\',\'\',\'width=250,height=100\');" class="menu">Re-Envoyer e-mail validation commande</a>';
	}
	$boutonFiche .= '</td>
		<td width="1"><img src="../images/images/button_04.png" width="7" height="18" /></td>
		</tr>
		</table></td>';
	
	if ($mailok > 0) {	
		$boutonFiche .= '<td>&nbsp;</td><td width="1">
		<table  border="0" cellspacing="0" cellpadding="0"><tr><td width="1"><img src="../images/images/button_01.png" width="15" height="18" /></td><td nowrap="nowrap" background="../images/images/button_02.png">';
		if ($mailok == 1) {
			$boutonFiche .= '<a href="javascript:void(0);" onClick="window.open(\'../mod_commandes/send_mail_expedition.php?id='.$id.'\',\'\',\'width=250,height=100\');" class="menu">Envoyer e-mail validation expédition</a>';
		}
		else  {
			$boutonFiche .= '<a href="javascript:void(0);" onClick="window.open(\'../mod_commandes/send_mail_expedition.php?id='.$id.'&mailok=2\',\'\',\'width=250,height=100\');" class="menu">Re-Envoyer e-mail validation expédition</a>';
		}
		$boutonFiche .= '</td><td width="1"><img src="../images/images/button_04.png" width="7" height="18" /></td></tr></table>
		</td>';
	}
	$boutonFiche .= '
	</tr>
	</table>';
}

// -------------------- COMMANDES --------------------------- //
$R1 = array(
	'table' => 					'mod_commandes',
	'titre' => 					'Commande',
	'titres' => 				'',
	'genre'=>					'e',
	'relation'=>				'parent:1',
	'rubrelation'=>				'',
	'childRel'=>				'',
	'rubLevel'=>				'',
	'prodLevel'=>				'',
	'wherenot'=>				'',
	'postbdd'=>					'',
	'preview'=>					'',
	'ifr '=>					'',
	'boutonFiche'=>				$boutonFiche,
	'boutonListe'=>				$boutonListe,
	'filtre'=>					array('statut_c'=>'2','statut_p'=>'todo'),
	'ordre'=>					'id DESC',
	'miseenavant'=>				'',
	'fixe'=>					0,
	'tips '=>					'',
	'rep'=>						$rep.'clients/',
	'sizeimg'=>					array(mini=>'95x120',medium=>'100x145',grand=>'360x480',tgrand=>'3600x4800'),
);


$R1_data = array(
	array(name=>'id'),
	
	array(name=>'statut_c',titre=>'Statut de la commande',sqlType=>'tinyint',nbChar=>'1',sqlDefaut=>'1',input=>'select',valeur=>array('1','2','3'),titrevaleur=>array('Non valide','A traiter','Trait&eacute;e'),index=>'1'),
	array(name=>'statut_p',titre=>'Statut du paiement',sqlType=>'tinyint',nbChar=>'1',sqlDefaut=>'1',input=>'select',valeur=>array('0','1'),titrevaleur=>array('Non valide','Valide'),index=>'1','tips'=>'Valid&eacute; par la banque ou l\'admin, suivant le moyen de paiement'), //,disable=>'1'
	
	array(name=>'mailok',titre=>'Email envoy&eacute;',sqlType=>'tinyint',nbChar=>'1',sqlDefaut=>'1',input=>'radio',valeur=>array('0','1','2'),titrevaleur=>array('Non','Email validation','Email expédition'),index=>'1',disable=>'1','tips'=>'Le mail avertissant de la validation et de l\'expédition de la commande a été envoy&eacute;'),
	array(
		'name'=>				'dateexpe',
		'titre'=>				'Exp&eacute;di&eacute;e le',
		'sqlType'=>				'datetime',
		'sqlDefaut'=>			'',
		'nbChar'=>				'',
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'datetime',
		'oblige'=>				'',
		'disable'=>				'',
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'A pr&eacute;ciser, pour pass&eacute;e la commande en statut &quot;Trait&eacute;e&quot;',
		'separateur'=>			'',
	),
	
	array(name=>'client_id',titre=>'Client',sqlType=>'int',nbChar=>'8',input=>'select',inc=>'mod_clients:id:nom-prenom',index=>'1',disable=>'1', tips=>'Fiche client : <a href="../mod_clients/index.php?mode=fiche&id=\'.$F->V[\'0\'][$this->data[$i][\'name\']].\'" target="_blank">Cliquer ici</a>', 'separateur'=>'INFOS COMMANDE'),
	
	array(name=>'titre',titre=>'R&eacute;f&eacute;rence',sqlType=>'varchar',nbChar=>'250',input=>'text',htmDefaut=>'post',index=>'1',oblige=>'1',disable=>'1'),
	
	array(
		'name'=>				'datecrea',
		'titre'=>				'Date',
		'sqlType'=>				'datetime',
		'sqlDefaut'=>			'',
		'nbChar'=>				'',
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'datetime',
		'oblige'=>				1,
		'disable'=>				1,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'',
		'separateur'=>			'',
	),

	array(name=>'transaction_total',titre=>'Total transaction (&euro;)',sqlType=>'float',nbChar=>'8,2',input=>'text',disable=>'1'),
	array(name=>'total',titre=>'Sous-Total (&euro;)',sqlType=>'float',nbChar=>'8,2',input=>'text',disable=>'1'),
	array(name=>'fdp',titre=>'Frais de port (&euro;)',sqlType=>'float',nbChar=>'8,2',input=>'text',disable=>'1'),
	array(name=>'poids',titre=>'Poids total (Kilo)',sqlType=>'float',nbChar=>'8,2',input=>'text',disable=>'1'),
	array(
		'name'=>				'facture',
		'titre'=>				'Facture PDF',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				70,
		'bilingue'=>			0,
		'input'=>				'file',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'fichier',
		'oblige'=>				'',
		'disable'=>				1,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'Formats : pdf, doc, xls, ...',
	),
	array(name=>'mode_p',titre=>'Mode paiement',sqlType=>'tinyint',nbChar=>'1',sqlDefaut=>'1',input=>'select',valeur=>array('1','2','3'),titrevaleur=>array('CB','VIREMENT','CHEQUE'),index=>'0',disable=>'1', 'separateur'=>'PAIEMENT'),

	array(name=>'transaction_id',titre=>'N° transaction',sqlType=>'varchar',nbChar=>'250',input=>'text',disable=>'1'),
	array(name=>'transaction_mode',titre=>'Mode transaction',sqlType=>'varchar',nbChar=>'250',input=>'text',disable=>'1'),
	array(name=>'transaction_heure',titre=>'Heure transaction',sqlType=>'varchar',nbChar=>'250',input=>'text',disable=>'1'),
	array(name=>'transaction_date',titre=>'Date transaction',sqlType=>'varchar',nbChar=>'250',input=>'text',disable=>'1'),
	array(name=>'response_code',titre=>'Code r&eacute;ponse',sqlType=>'varchar',nbChar=>'8',sqlDefaut=>'1',input=>'select',valeur=>array('','00000','00003','00004','00006','00008','00009','00010','00011','00015','00016','00021'),titrevaleur=>array('','Op&eacute;ration r&eacute;ussie','Erreur e-transactions','Num&eacute;ro de porteur ou cryptogramme visuel invalide','Accès refus&eacute; ou site/rang/identifiant incorrect','Date de fin de validit&eacute; incorrecte','Erreur v&eacute;rification comportementale','Devise inconnue','Montant incorrect','Paiement d&eacute;jà effectu&eacute;','Inutilis&eacute;','Carte non autoris&eacute;e'),disable=>'1'),
	array(name=>'authorisation_id',titre=>'Autorisation ID',sqlType=>'varchar',nbChar=>'250',input=>'text',disable=>'1'),
	array(name=>'transaction_devise',titre=>'Code devise',sqlType=>'varchar',nbChar=>'250',sqlDefaut=>'',input=>'select',valeur=>array('978'),titrevaleur=>array('Euro'),disable=>'1'),

	array(
		'name'=>				'civilite',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				4,
		'bilingue'=>			0,
		'input'=>				'select',
		'valeur'=>				array('Mr','Mme','Mlle'),
		'titrevaleur'=>			array('Mr','Mme','Mlle'),
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				'',
		'tips'=>				'',
		'separateur'=>			'CLIENT'
	),
	array(
		'name'=>				'nom',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				'',
		'tips'=>				''
	),
	array(
		'name'=>				'prenom',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				'',
		'tips'=>				''
	),

	array(
		'name'=>				'email',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				250,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				'',
		'tips'=>				''
	),
	
	array(
		'name'=>				'adresse',
		'titre'=>				'Adresse',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				250,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
		'separateur'=>			'Adresse facturation',
	),
	array(
		'name'=>				'cp',
		'titre'=>				'Code postal',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>					'',
	),
	array(
		'name'=>				'ville',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
	),
	array(
		'name'=>				'pays',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
	),

	array(
		'name'=>				'tel',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
	),
	
	
	
	array(
		'name'=>				'adresse2',
		'titre'=>				'Adresse2',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				250,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
		'separateur'=>			'Adresse livraison',
	),
	array(
		'name'=>				'cp2',
		'titre'=>				'Code postal2',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>					'',
	),
	array(
		'name'=>				'ville2',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
	),
	array(
		'name'=>				'pays2',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
	),
	array(
		'name'=>				'zone2',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				4,
		'bilingue'=>			0,
		'input'=>				'select',
		'valeur'=>				array_keys($arr_Zones),
		'titrevaleur'=>			array_values($arr_Zones),
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				'',
		'tips'=>				''
	),
	array(
		'name'=>				'tel2',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
	),
	

	array(name=>'commentaire',titre=>'Commentaire admin.',sqlType=>'text',input=>'textarea',wysiwyg=>'0', 'separateur'=>'CHAMPS ADMIN'),

	

);
//$C = new SQL($R1); $C->createSQL($R1_data,'1');
//$C = new SQL($R1); $C->addSQL($R1_data);




// -------------------- COMMANDES --------------------------- //
$R2 = array(
	'table' => 					'mod_commandes_produits',
	'titre' => 					'Produit commandé',
	'titres' => 				'Produits commandés',
	'genre'=>					'',
	'relation'=>				$R1['table'].':id:titre:commande_id',
	'rubrelation'=>				'',
	'childRel'=>				'',
	'rubLevel'=>				'',
	'prodLevel'=>				'',
	'wherenot'=>				'',
	'postbdd'=>					'',
	'preview'=>					'',
	'ifr '=>					'',
	'boutonFiche'=>				'',
	'boutonListe'=>				'',
	'filtre'=>					'', //array('statut_c'=>'2','statut_p'=>'todo'),
	'ordre'=>					'id DESC',
	'miseenavant'=>				'nom',
	'fixe'=>					0,
	'tips '=>					'',
	'rep'=>						$rep.'clients/',
	'sizeimg'=>					array(mini=>'95x120',medium=>'100x145',grand=>'360x480',tgrand=>'3600x4800'),
);


$R2_data = array(
	array(name=>'id'),
	array(name=>'commande_id',titre=>'Commande',sqlType=>'int',nbChar=>'8',input=>'select',relation=>'1',index=>'1',disable=>'1'),
	array(
		'name'=>				'produit_id',
		'titre'=>				'Produit',
		'sqlType'=>				'int',
		'sqlDefaut'=>			1,
		'nbChar'=>				8,
		'bilingue'=>			0,
		'input'=>				'select',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			1,
		'inc'=>					'mod_catalogue_produits:id:titre',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				''
	),
	array(
		'name'=>				'quantite',
		'titre'=>				'',
		'sqlType'=>				'int',
		'sqlDefaut'=>			1,
		'nbChar'=>				8,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			1,
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				''
	),
	array(
		'name'=>				'format',
		'titre'=>				'Format/Matière',
		'sqlType'=>				'char',
		'sqlDefaut'=>			1,
		'nbChar'=>				2,
		'bilingue'=>			0,
		'input'=>				'select',
		'valeur'=>				array_keys($arr_Formats),
		'titrevaleur'=>			array_values($arr_Formats),
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				''
	),
	array( 
		'name'=>				'echelle',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				10,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'0',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'Ex. : 1/8<br />
								Laisser 0 pour les fichers 3D'
	),
	array(
		'name'=>				'prix',
		'titre'=>				'Prix TTC',
		'sqlType'=>				'float',
		'sqlDefaut'=>			'',
		'nbChar'=>				'8,2',
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'En &euro;',
		'separateur'=>			'',
	),
	array(
		'name'=>				'prix_promo',
		'titre'=>				'Prix promo TTC',
		'sqlType'=>				'float',
		'sqlDefaut'=>			'',
		'nbChar'=>				'8,2',
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'En &euro;',
		'separateur'=>			'',
	),
	array(
		'name'=>				'prix_total',
		'titre'=>				'Prix total TTC',
		'sqlType'=>				'float',
		'sqlDefaut'=>			'',
		'nbChar'=>				'8,2',
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'En &euro;',
		'separateur'=>			'',
	),
	array(
		'name'=>				'poids_total',
		'titre'=>				'Poids total',
		'sqlType'=>				'float',
		'sqlDefaut'=>			'',
		'nbChar'=>				'8,2',
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'En kilo',
		'separateur'=>			'',
	),

);
//$C = new SQL($R2); $C->createSQL($R2_data,'1');
//$C = new SQL($R2); $C->addSQL($R2_data);
?>