<?
define("_ADRESSE_", "Adresse");
define("_AERIEN_", "A&eacute;rien");
define("_ANNEES_", "Ann&eacute;es");
define("_AUTRE_", "Autre");
define("_CARACTERISTIQUES_", "Caract&eacute;ristiques");
define("_CARTON_", "Carton");
define("_CHOISIR_", "Choisir");
define("_CODE_POSTAL_", "Code postal");
define("_COMMERCIAUX_DISTRIBUTEURS_", "Contact commerciaux et distributeurs");
define("_COMMUNIQUE_ARCHIVE_", "Communiqu&eacute; de presse - archives");
define("_COMMUNIQUE_UNE_", "Communiqu&eacute; de presse &agrave; la une");
define("_CONCEPTION_MESURE_", "Conception sur mesure");
define("_CONTACT_COMMERCIAUX_", "Contacts commerciaux");
define("_COORDONNEES_", "Coordonn&eacute;es");
define("_DIMENSION_", "Dimension");
define("_DIMENSION_PRODUIT_", "Dimensions externes de votre produit");
define("_DISTRIBUTEURS_", "Distributeurs");
define("_DONNEES_PERSONNELLES_", "Donn&eacute;es personnelles");
define("_DUREE_EXPEDITION_", "Dur&eacute;e d'exp&eacute;dition");
define("_DUREE_TRANSPORT_", "Dur&eacute;e de transport");
define("_EMAIL_", "Email");
define("_EMBALLAGE_", "Emballage");
define("_EMPLOI_", "Emploi");
define("_ENVOYER_", "Envoyer");
define("_EXPERTISE_", "Expertise");
define("_FAX_", "Fax");
define("_FORMULAIRE_CONTACT_", "Formulaire de contact");
define("_FORMULAIRE_CONTACT_PRODUIT_", "Pour poser votre question veuillez remplir le formulaire");
define("_FORM_ANNEE_MOIS_", "Vous devez s&eacute;lectionner l'ann&eacute;e et le mois");
define("_FORM_DIMENSION1_", "Le champs dimension (L) est obligatoire");
define("_FORM_DIMENSION2_", "Le champs dimension (l) est obligatoire");
define("_FORM_DIMENSION3_", "Le champs dimension (h) est obligatoire");
define("_FORM_DUREE_", "Le champs temp&eacute;rature est obligatoire");
define("_FORM_EMAIL_", "Vous devez pr&eacute;ciser un email valide");
define("_FORM_MESSAGE_", "Le champs message est obligatoire");
define("_FORM_MOTDEPASSE_", "Le champs mot de passe est obligatoire");
define("_FORM_NATURE_", "Le champs nature de votre demande est obligatoire");
define("_FORM_NB_EMBALLAGE_", "Le champs nombre d'emballage est obligatoire");
define("_FORM_NB_LIVRAISON_", "Le champs nombre de livraison est obligatoire");
define("_FORM_NOM_", "Le champs nom est obligatoire");
define("_FORM_PRENOM_", "Le champs pr&eacute;nom est obligatoire");
define("_FORM_QUESTION_", "Le champs question est obligatoire");
define("_FORM_SOCIETE_", "Le champs soci&eacute;t&eacute; est obligatoire");
define("_FORM_TEMPERATURE_", "Le champs temp&eacute;rature est obligatoire");
define("_FORM_TEMPERATURE_EXT_", "Le champs temp&eacute;rature ext&eacute;rieure est obligatoire");
define("_FORM_TRANSPORT_", "Le champs mode de transport est obligatoire");
define("_FORM_TYPE_", "Le champs type de votre demande est obligatoire");
define("_FORM_TYPE_EMBALLAGE_", "Le champs temp&eacute;rature ext&eacute;rieure est obligatoire");
define("_HAUTEUR_", "h");
define("_HAUT_PAGE_", "Haut de page");
define("_HEURES_", "heures");
define("_IMPORTER_PROFIL_TEMPERATURE_", "Importez votre profil de temp&eacute;rature");
define("_LARGEUR_", "L");
define("_LIQUIDE_", "Liquide");
define("_LISTE_MOIS_", "Janvier F&eacute;vrier Mars Avril Mai Juin Juillet Ao&ucirc;t Septembre Octobre Novembre D&eacute;cembre");
define("_LONGUEUR_", "l");
define("_MANQUE_VARIABLE_", "D&eacute;sol&eacute; il manque une variable");
define("_MEDICAMENTS_", "M&eacute;dicaments");
define("_MESSAGE_CONTACT_DEVIS_", "Votre cahier des charges nous a bien &eacute;t&eacute; transmis. Nous vous remercions de votre confiance. Nous traitons votre demande dans les meilleurs d&eacute;lais.");
define("_MIXTE_", "Mixte");
define("_MOIS_", "Mois");
define("_MOYEN_TRANSPORT_", "Moyen de transport");
define("_NATURE_DEMANDE_", "Nature de votre demande");
define("_NATURE_PRODUIT_", "Nature de produit");
define("_NOM_", "Nom");
define("_NOMBRE_EMBALLAGE_", "Nombre d'emballage par livraison");
define("_NOMBRE_LIVRAISON_", "Nombre de livraison par an");
define("_NOM_CONTENANCE_", "Nom / Contenance");
define("_NOS_PRODUITS_", "Nos produits");
define("_OBTENIR_DEVIS_", "Pour obtenir un devis veuillez remplir le formulaire ci dessous. Tous les champs sont obligatoires, alors attention.");
define("_PAS_DE_COMMUNIQUE_", "Pas de communiqu&eacute; &agrave; &quot;la une&quot; pour le moment");
define("_PAS_D_ARTICLE_", "Pas d'article pour cette date");
define("_PAYS_", "Pays");
define("_PLAGE_TEMPERATURE_", "Plage de temp&eacute;rature");
define("_PLASTIQUE_", "Plastique");
define("_POUDRE_", "Poudre");
define("_POUR_NOUS_CONTACTER_", "Pour nous contacter veuillez remplir le formulaire suivant");
define("_PRECISION_", "Pr&eacute;cision");
define("_PRENOM_", "Pr&eacute;nom");
define("_PRESENTATION_", "Pr&eacute;sentation");
define("_PRODUITS_", "Produits");
define("_PRODUITS_AGROALIMENTAIRES_", "Produits agroalimentaires");
define("_PRODUITS_CHIMIQUES_", "Produits chimiques");
define("_SAVOIR_FAIRE_", "Savoir-faire");
define("_SELECTION_DATE_", "S&eacute;lectionnez une date");
define("_SERVICE_", "Service/Fonction");
define("_SOCIETE_", "Soci&eacute;t&eacute;");
define("_SOLIDE_", "solide");
define("_TELEPHONE_", "T&eacute;l&eacute;phone");
define("_TEMPERATURE_EXTERIEURE_", "Temp&eacute;rature ext&eacute;rieure moyenne durant le transport (ou joignez votre profil de temp&eacute;rature )");
define("_TERRESTRE_", "Terrestre");
define("_TISSUS_", "Tissus");
define("_TYPE_EMBALLAGE_", "Type d'emballage");
define("_TYPE_PRODUIT_", "Type de produit");
define("_VILLE_", "Ville");
define("_VOTRE_BESOIN_", "Votre besoin");
define("_VOTRE_LOGISTIQUE_", "Votre Logistique");
define("_VOTRE_PRODUIT_", "Votre produit");
define("_VOTRE_QUESTION_", "Votre question");

?>