<?

$id = gpc('id');

$boutonFiche = '<table  border="0" cellspacing="0" cellpadding="0">
<tr>
<td width="1">
	<table  border="0" cellspacing="0" cellpadding="0">
	<tr>
	<td width="1"><img src="../images/images/button_01.png" width="15" height="18" /></td>
	<td nowrap="nowrap" background="../images/images/button_02.png"><a href="javascript:void(0);" onClick="window.open(\'../mod_clients/send.php?id='.$id.'\',\'\',\'width=250,height=100\');" class="menu">Envoyer e-mail info de connexion au client</a></td>
	<td width="1"><img src="../images/images/button_04.png" width="7" height="18" /></td>
	</tr>
	</table></td>
</tr>
</table>';

// -------------------- CATEGORIES --------------------------- //
$R1 = array(
	'table' => 					'mod_clients',
	'titre' => 					'Client',
	'titres' => 				'',
	'genre'=>					'',
	'relation'=>				'parent:2',
	'rubrelation'=>				'',
	'childRel'=>				'',
	'rubLevel'=>				'',
	'prodLevel'=>				'',
	'wherenot'=>				'',
	'postbdd'=>					'',
	'preview'=>					'',
	'ifr '=>					'',
	'boutonFiche'=>				$boutonFiche,
	'boutonListe'=>				'',
	'filtre'=>					array('actif'=>'todo'),
	'ordre'=>					'id DESC',
	'miseenavant'=>				'nom',
	'fixe'=>					'',
	'tips '=>					'',
	'rep'=>						'',
	'sizeimg'=>					'',
);

$R1_data = array(
	array('name'=>'id'),
	array('name'=>'ids', 'sqlDefaut'=>'', 'sqlType'=>'varchar', 'nbChar'=>'100'),
	array(
		'name'=>				'actif',
		'titre'=>				'Visible',
		'sqlType'=>				'tinyint',
		'sqlDefaut'=>			1,
		'nbChar'=>				1,
		'bilingue'=>			0,
		'input'=>				'radio',
		'valeur'=>				array('1','0'),
		'titrevaleur'=>			array('Oui','Non'),
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'',
		'separateur'=>			'',
	),
	array(
		'name'=>				'datecrea',
		'titre'=>				'Date',
		'sqlType'=>				'datetime',
		'sqlDefaut'=>			'',
		'nbChar'=>				'',
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'datetime',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'Ex. : '.getDateTime(),
		'separateur'=>			'',
	),
	array(
		'name'=>				'civilite',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				4,
		'bilingue'=>			0,
		'input'=>				'select',
		'valeur'=>				array('Mr','Mme','Mlle'),
		'titrevaleur'=>			array('Mr','Mme','Mlle'),
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'',
		'separateur'=>			'INFORMATIONS PERSONNELLES'
	),
	array(
		'name'=>				'nom',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				''
	),
	array(
		'name'=>				'prenom',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				''
	),

	array(
		'name'=>				'email',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				250,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				''
	),
	
	array(
		'name'=>				'm2p',
		'titre'=>				'Mot de passe',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				50,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				'',
		'tips'=>				''
	),

	array(
		'name'=>				'adresse',
		'titre'=>				'Adresse',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				250,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
		'separateur'=>			'Adresse facturation',
	),
	array(
		'name'=>				'cp',
		'titre'=>				'Code postal',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>					'',
	),
	array(
		'name'=>				'ville',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
	),
	array(
		'name'=>				'pays',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
	),
	array(
		'name'=>				'zone',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				4,
		'bilingue'=>			0,
		'input'=>				'select',
		'valeur'=>				array_keys($arr_Zones),
		'titrevaleur'=>			array_values($arr_Zones),
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				'',
		'tips'=>				''
	),
	array(
		'name'=>				'tel',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
	),
	
);
//$C = new SQL($R1); $C->createSQL($R1_data,'1');
//$C = new SQL($R1); $C->addSQL($R1_data);



$boutonListe = '';//<table  border="0" cellspacing="0" cellpadding="0"><tr><td width="1"><img src="../images/images/button_01.png" width="15" height="18" /></td><td nowrap="nowrap" background="../images/images/button_02.png"><a href="javascript:void(0);" onclick="window.open(\'../mod_clients/commandes_purge.php\',\'\',\'toolbar=yes,location=yes,status=yes,menubar=yes,scrollbars=yes,resizable=yes,width=600,height=600\');" class="menu">Purger les commandes temporaires</a></td><td width="1"><img src="../images/images/button_04.png" width="7" height="18" /></td></tr></table>';

$id = gpc('id');
if ($id > 0) {
	$A = new SQL('mod_commandes');
	$A->LireSql(array('*')," id='$id' LIMIT 1 ");
	$mailok = Aff($A->V[0]['mailok']);

	$boutonFiche = '<table  border="0" cellspacing="0" cellpadding="0">
	<tr>
	<td width="1">
	<table  border="0" cellspacing="0" cellpadding="0"><tr><td width="1"><img src="../images/images/button_01.png" width="15" height="18" /></td><td nowrap="nowrap" background="../images/images/button_02.png"><a href="javascript:void(0);" onclick="window.open(\'../mod_commandes/commande_impression.php?commande_id='.$id.'\',\'\',\'toolbar=yes,location=yes,status=yes,menubar=yes,scrollbars=yes,resizable=yes,width=600,height=600\');" class="menu">D&eacute;tail de la commande (Imprimer)</a></td><td width="1"><img src="../images/images/button_04.png" width="7" height="18" /></td></tr></table>
	</td><td>&nbsp;</td><td>
		<table  border="0" cellspacing="0" cellpadding="0">
		<tr>
		<td width="1"><img src="../images/images/button_01.png" width="15" height="18" /></td>
		<td nowrap="nowrap" background="../images/images/button_02.png">';
	if ($mailok < 1) {
		$boutonFiche .= '<a href="javascript:void(0);" onClick="window.open(\'../mod_commandes/send_mail.php?id='.$id.'\',\'\',\'width=250,height=100\');" class="menu">Envoyer e-mail validation commande</a>';
	}
	else  {
		$boutonFiche .= '<a href="javascript:void(0);" onClick="window.open(\'../mod_commandes/send_mail.php?id='.$id.'&mailok=1\',\'\',\'width=250,height=100\');" class="menu">Re-Envoyer e-mail validation commande</a>';
	}
	$boutonFiche .= '</td>
		<td width="1"><img src="../images/images/button_04.png" width="7" height="18" /></td>
		</tr>
		</table></td>';
	
	if ($mailok > 0) {	
		$boutonFiche .= '<td>&nbsp;</td><td width="1">
		<table  border="0" cellspacing="0" cellpadding="0"><tr><td width="1"><img src="../images/images/button_01.png" width="15" height="18" /></td><td nowrap="nowrap" background="../images/images/button_02.png">';
		if ($mailok == 1) {
			$boutonFiche .= '<a href="javascript:void(0);" onClick="window.open(\'../mod_commandes/send_mail_expedition.php?id='.$id.'\',\'\',\'width=250,height=100\');" class="menu">Envoyer e-mail validation expédition</a>';
		}
		else  {
			$boutonFiche .= '<a href="javascript:void(0);" onClick="window.open(\'../mod_commandes/send_mail_expedition.php?id='.$id.'&mailok=2\',\'\',\'width=250,height=100\');" class="menu">Re-Envoyer e-mail validation expédition</a>';
		}
		$boutonFiche .= '</td><td width="1"><img src="../images/images/button_04.png" width="7" height="18" /></td></tr></table>
		</td>';
	}
	$boutonFiche .= '
	</tr>
	</table>';
}



// -------------------- COMMANDES --------------------------- //
$R2 = array(
	'table' => 					'mod_commandes',
	'titre' => 					'Commande',
	'titres' => 				'',
	'genre'=>					'e',
	'relation'=>				$R1['table'].':id:nom-prenom:client_id',
	'rubrelation'=>				'',
	'childRel'=>				'',
	'rubLevel'=>				'',
	'prodLevel'=>				'',
	'wherenot'=>				'',
	'postbdd'=>					'',
	'preview'=>					'',
	'ifr '=>					'',
	'boutonFiche'=>				$boutonFiche,
	'boutonListe'=>				$boutonListe,
	'filtre'=>					array('statut_c'=>'2','statut_p'=>'todo'),
	'ordre'=>					'id DESC',
	'miseenavant'=>				'nom',
	'fixe'=>					0,
	'tips '=>					'',
	'rep'=>						$rep.'clients/',
	'sizeimg'=>					array(mini=>'95x120',medium=>'100x145',grand=>'360x480',tgrand=>'3600x4800'),
);


$R2_data = array(
	array(name=>'id'),

	array(name=>'statut_c',titre=>'Statut de la commande',sqlType=>'tinyint',nbChar=>'1',sqlDefaut=>'1',input=>'select',valeur=>array('1','2','3'),titrevaleur=>array('Non valide','A traiter','Traitée'),index=>'1'),
	
	array(name=>'statut_p',titre=>'Statut du paiement',sqlType=>'tinyint',nbChar=>'1',sqlDefaut=>'1',input=>'select',valeur=>array('0','1'),titrevaleur=>array('Non valide','Valide'),index=>'1',disable=>'1'),
	array(name=>'mailok',titre=>'Email envoyé',sqlType=>'tinyint',nbChar=>'1',sqlDefaut=>'1',input=>'radio',valeur=>array('0','1'),titrevaleur=>array('Non','Oui'),index=>'1',disable=>'1','tips'=>'Le mail avertissant de la validation de la commande est envoyé'),
	
	array(name=>'client_id',titre=>'Client',sqlType=>'int',nbChar=>'8',input=>'select',relation=>'1',index=>'1',disable=>'1', 'separateur'=>'INFOS COMMANDE'),
	
	array(name=>'titre',titre=>'Référence',sqlType=>'varchar',nbChar=>'250',input=>'text',htmDefaut=>'post',index=>'1',oblige=>'1',disable=>'1'),
	
	array(
		'name'=>				'datecrea',
		'titre'=>				'Date',
		'sqlType'=>				'datetime',
		'sqlDefaut'=>			'',
		'nbChar'=>				'',
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'datetime',
		'oblige'=>				1,
		'disable'=>				1,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'',
		'separateur'=>			'',
	),

	array(name=>'transaction_total',titre=>'Total transaction (&euro;)',sqlType=>'float',nbChar=>'8,2',input=>'text',disable=>'1'),
	array(name=>'total',titre=>'Sous-Total (&euro;)',sqlType=>'float',nbChar=>'8,2',input=>'text',disable=>'1'),
	array(name=>'fdp',titre=>'Frais de port (&euro;)',sqlType=>'float',nbChar=>'8,2',input=>'text',disable=>'1'),
	array(name=>'poids',titre=>'Poids total (Kilo)',sqlType=>'float',nbChar=>'8,2',input=>'text',disable=>'1'),
	array(
		'name'=>				'facture',
		'titre'=>				'Facture PDF',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				70,
		'bilingue'=>			0,
		'input'=>				'file',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'fichier',
		'oblige'=>				'',
		'disable'=>				1,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'Formats : pdf, doc, xls, ...',
	),
	array(name=>'mode_p',titre=>'Mode paiement',sqlType=>'tinyint',nbChar=>'1',sqlDefaut=>'1',input=>'select',valeur=>array('1','2','3'),titrevaleur=>array('CB','VIREMENT','CHEQUE'),index=>'0',disable=>'1', 'separateur'=>'PAIEMENT'),

	array(name=>'transaction_id',titre=>'N° transaction',sqlType=>'varchar',nbChar=>'250',input=>'text',disable=>'1'),
	array(name=>'transaction_mode',titre=>'Mode transaction',sqlType=>'varchar',nbChar=>'250',input=>'text',disable=>'1'),
	array(name=>'transaction_heure',titre=>'Heure transaction',sqlType=>'varchar',nbChar=>'250',input=>'text',disable=>'1'),
	array(name=>'transaction_date',titre=>'Date transaction',sqlType=>'varchar',nbChar=>'250',input=>'text',disable=>'1'),
	array(name=>'response_code',titre=>'Code réponse',sqlType=>'varchar',nbChar=>'8',sqlDefaut=>'1',input=>'select',valeur=>array('','00000','00003','00004','00006','00008','00009','00010','00011','00015','00016','00021'),titrevaleur=>array('','Opération réussie','Erreur e-transactions','Numéro de porteur ou cryptogramme visuel invalide','Accès refusé ou site/rang/identifiant incorrect','Date de fin de validité incorrecte','Erreur vérification comportementale','Devise inconnue','Montant incorrect','Paiement déjà effectué','Inutilisé','Carte non autorisée'),disable=>'1'),
	array(name=>'authorisation_id',titre=>'Autorisation ID',sqlType=>'varchar',nbChar=>'250',input=>'text',disable=>'1'),
	array(name=>'transaction_devise',titre=>'Code devise',sqlType=>'varchar',nbChar=>'250',sqlDefaut=>'',input=>'select',valeur=>array('978'),titrevaleur=>array('Euro'),disable=>'1'),

	array(
		'name'=>				'civilite',

		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				4,
		'bilingue'=>			0,
		'input'=>				'select',
		'valeur'=>				array('Mr','Mme','Mlle'),
		'titrevaleur'=>			array('Mr','Mme','Mlle'),
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				'',
		'tips'=>				'',
		'separateur'=>			'CLIENT'
	),
	array(
		'name'=>				'nom',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				'',
		'tips'=>				''
	),
	array(
		'name'=>				'prenom',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				'',
		'tips'=>				''
	),

	array(
		'name'=>				'email',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				250,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				'',
		'tips'=>				''
	),
	
	array(
		'name'=>				'm2p',
		'titre'=>				'Mot de passe',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				50,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				'',
		'tips'=>				''
	),
	
	
	
	
	array(
		'name'=>				'adresse',
		'titre'=>				'Adresse',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				250,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
		'separateur'=>			'Adresse facturation',
	),
	array(
		'name'=>				'cp',
		'titre'=>				'Code postal',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>					'',
	),
	array(
		'name'=>				'ville',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
	),
	array(
		'name'=>				'pays',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
	),

	array(
		'name'=>				'tel',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
	),
	
	
	
	array(
		'name'=>				'adresse2',
		'titre'=>				'Adresse2',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				250,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
		'separateur'=>			'Adresse livraison',
	),
	array(
		'name'=>				'cp2',
		'titre'=>				'Code postal2',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>					'',
	),
	array(
		'name'=>				'ville2',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
	),
	array(
		'name'=>				'pays2',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
	),
	array(
		'name'=>				'zone2',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				4,
		'bilingue'=>			0,
		'input'=>				'select',
		'valeur'=>				array_keys($arr_Zones),
		'titrevaleur'=>			array_values($arr_Zones),
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				'',
		'tips'=>				''
	),
	array(
		'name'=>				'tel2',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
	),
	

	array(name=>'commentaire',titre=>'Commentaire admin.',sqlType=>'text',input=>'textarea',wysiwyg=>'0', 'separateur'=>'CHAMPS ADMIN'),

);
//$C = new SQL($R2); $C->createSQL($R2_data,'1');
//$C = new SQL($R2); $C->addSQL($R2_data);


?>
<?



$boutonListe = '';//<table  border="0" cellspacing="0" cellpadding="0"><tr><td width="1"><img src="../images/images/button_01.png" width="15" height="18" /></td><td nowrap="nowrap" background="../images/images/button_02.png"><a href="javascript:void(0);" onclick="window.open(\'../mod_clients/commandes_purge.php\',\'\',\'toolbar=yes,location=yes,status=yes,menubar=yes,scrollbars=yes,resizable=yes,width=600,height=600\');" class="menu">Purger les commandes temporaires</a></td><td width="1"><img src="../images/images/button_04.png" width="7" height="18" /></td></tr></table>';

$id = gpc('id');
if ($id > 0) {
	$A = new SQL('mod_commandes');
	$A->LireSql(array('*')," id='$id' LIMIT 1 ");
	$mailok = Aff($A->V[0]['mailok']);

	$boutonFiche = '<table  border="0" cellspacing="0" cellpadding="0">
	<tr>
	<td width="1">
	<table  border="0" cellspacing="0" cellpadding="0"><tr><td width="1"><img src="../images/images/button_01.png" width="15" height="18" /></td><td nowrap="nowrap" background="../images/images/button_02.png"><a href="javascript:void(0);" onclick="window.open(\'../mod_commandes/commande_impression.php?commande_id='.$id.'\',\'\',\'toolbar=yes,location=yes,status=yes,menubar=yes,scrollbars=yes,resizable=yes,width=600,height=600\');" class="menu">D&eacute;tail de la commande (Imprimer)</a></td><td width="1"><img src="../images/images/button_04.png" width="7" height="18" /></td></tr></table>
	</td><td>&nbsp;</td><td>
		<table  border="0" cellspacing="0" cellpadding="0">
		<tr>
		<td width="1"><img src="../images/images/button_01.png" width="15" height="18" /></td>
		<td nowrap="nowrap" background="../images/images/button_02.png">';
	if ($mailok < 1) {
		$boutonFiche .= '<a href="javascript:void(0);" onClick="window.open(\'../mod_commandes/send_mail.php?id='.$id.'\',\'\',\'width=250,height=100\');" class="menu">Envoyer e-mail validation commande</a>';
	}
	else  {
		$boutonFiche .= '<a href="javascript:void(0);" onClick="window.open(\'../mod_commandes/send_mail.php?id='.$id.'&mailok=1\',\'\',\'width=250,height=100\');" class="menu">Re-Envoyer e-mail validation commande</a>';
	}
	$boutonFiche .= '</td>
		<td width="1"><img src="../images/images/button_04.png" width="7" height="18" /></td>
		</tr>
		</table></td>';
	
	if ($mailok > 0) {	
		$boutonFiche .= '<td>&nbsp;</td><td width="1">
		<table  border="0" cellspacing="0" cellpadding="0"><tr><td width="1"><img src="../images/images/button_01.png" width="15" height="18" /></td><td nowrap="nowrap" background="../images/images/button_02.png">';
		if ($mailok == 1) {
			$boutonFiche .= '<a href="javascript:void(0);" onClick="window.open(\'../mod_commandes/send_mail_expedition.php?id='.$id.'\',\'\',\'width=250,height=100\');" class="menu">Envoyer e-mail validation expédition</a>';
		}
		else  {
			$boutonFiche .= '<a href="javascript:void(0);" onClick="window.open(\'../mod_commandes/send_mail_expedition.php?id='.$id.'&mailok=2\',\'\',\'width=250,height=100\');" class="menu">Re-Envoyer e-mail validation expédition</a>';
		}
		$boutonFiche .= '</td><td width="1"><img src="../images/images/button_04.png" width="7" height="18" /></td></tr></table>
		</td>';
	}
	$boutonFiche .= '
	</tr>
	</table>';
}


// -------------------- COMMANDES --------------------------- //
$R3 = array(
	'table' => 					'mod_devis',
	'titre' => 					'Demande de devis',
	'titres' => 				'Demandes de devis',
	'genre'=>					'e',
	'relation'=>				$R1['table'].':id:nom-prenom:client_id',
	'rubrelation'=>				'',
	'childRel'=>				'',
	'rubLevel'=>				'',
	'prodLevel'=>				'',
	'wherenot'=>				'',
	'postbdd'=>					'',
	'preview'=>					'',
	'ifr '=>					'',
	'boutonFiche'=>				$boutonFiche,
	'boutonListe'=>				$boutonListe,
	'filtre'=>					array('statut_c'=>'2','statut_p'=>'todo'),
	'ordre'=>					'id DESC',
	'miseenavant'=>				'',
	'fixe'=>					0,
	'tips '=>					'',
	'rep'=>						$rep.'clients_devis/',
	'sizeimg'=>					array(mini=>'95x120',medium=>'100x145',grand=>'360x480',tgrand=>'3600x4800'),
);


$R3_data = array(
	array(name=>'id'),
	
	array(name=>'statut_c',titre=>'Statut de la commande',sqlType=>'tinyint',nbChar=>'1',sqlDefaut=>'1',input=>'select',valeur=>array('1','2','3','4'),titrevaleur=>array('Non valide','Attente du fichier','A traiter','Trait&eacute;e'),index=>'1'),
	array(name=>'statut_p',titre=>'Statut du paiement',sqlType=>'tinyint',nbChar=>'1',sqlDefaut=>'1',input=>'select',valeur=>array('0','1'),titrevaleur=>array('Attente','Valide'),index=>'1','tips'=>'Valid&eacute; par la banque ou l\'admin, suivant le moyen de paiement'),
	
	array(name=>'mailok',titre=>'Email envoy&eacute;',sqlType=>'tinyint',nbChar=>'1',sqlDefaut=>'1',input=>'radio',valeur=>array('0','1'),titrevaleur=>array('Non','Oui'),index=>'1',disable=>'1','tips'=>'Le mail avertissant de la validation de la commande est envoy&eacute;'),
	
	array(
		'name'=>				'dateexpe',
		'titre'=>				'Exp&eacute;di&eacute;e le',
		'sqlType'=>				'datetime',
		'sqlDefaut'=>			'',
		'nbChar'=>				'',
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'datetime',
		'oblige'=>				'',
		'disable'=>				'',
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'A pr&eacute;ciser, une fois la commande pass&eacute;e en statut &quot;Trait&eacute;e&quot;',
		'separateur'=>			'',
	),
	
	array(name=>'client_id',titre=>'Client',sqlType=>'int',nbChar=>'8',input=>'select',relation=>'1',index=>'1',disable=>'1', 'separateur'=>'INFOS DEVIS'),
	
	array(name=>'titre',titre=>'R&eacute;f&eacute;rence',sqlType=>'varchar',nbChar=>'250',input=>'text',htmDefaut=>'post',index=>'1',oblige=>'1',disable=>'1'),
	
	array(
		'name'=>				'datecrea',
		'titre'=>				'Date',
		'sqlType'=>				'datetime',
		'sqlDefaut'=>			'',
		'nbChar'=>				'',
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'datetime',
		'oblige'=>				1,
		'disable'=>				1,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'',
		'separateur'=>			'',
	),
	
	array(
		'name'=>				'souhaits',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				4,
		'bilingue'=>			0,
		'input'=>				'select',
		'valeur'=>				array('1','2','3'),
		'titrevaleur'=>			array('Mat&eacute;rialiser un fichier 3D', 'Cr&eacute;er une r&eacute;plique', 'Cr&eacute;er un fichier 3D'),
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				'',
		'tips'=>				'',
		'separateur'=>			''
	),
	array(
		'name'=>				'nom_fichier',
		'titre'=>				'Nom du fichier',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				'',
		'tips'=>				''
	),

	array(
		'name'=>				'format_fichier',
		'titre'=>				'Format fichier',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				20,
		'bilingue'=>			0,
		'input'=>				'select',
		'valeur'=>				array_keys($arr_Fichier_Formats),
		'titrevaleur'=>			array_values($arr_Fichier_Formats),
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				'',
		'tips'=>				'',
		'separateur'=>			''
	),
	array(
		'name'=>				'fichier',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				70,
		'bilingue'=>			0,
		'input'=>				'file',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'fichier',
		'oblige'=>				'',
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				1,
		'tips'=>				'Formats : vrml, ...',
	),

	
	array(
		'name'=>				'civilite',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				4,
		'bilingue'=>			0,
		'input'=>				'select',
		'valeur'=>				array('Mr','Mme','Mlle'),
		'titrevaleur'=>			array('Mr','Mme','Mlle'),
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				'',
		'tips'=>				'',
		'separateur'=>			'CLIENT'
	),
	array(
		'name'=>				'nom',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				'',
		'tips'=>				''
	),
	array(
		'name'=>				'prenom',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				'',
		'tips'=>				''
	),

	array(
		'name'=>				'email',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				250,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				1,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				'',
		'tips'=>				''
	),
	
	array(
		'name'=>				'adresse',
		'titre'=>				'Adresse',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				250,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
		'separateur'=>			'Adresse',
	),
	array(
		'name'=>				'cp',
		'titre'=>				'Code postal',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>					'',
	),
	array(
		'name'=>				'ville',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
	),
	array(
		'name'=>				'pays',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
	),

	array(
		'name'=>				'tel',
		'titre'=>				'',
		'sqlType'=>				'varchar',
		'sqlDefaut'=>			'',
		'nbChar'=>				150,
		'bilingue'=>			0,
		'input'=>				'text',
		'valeur'=>				'',
		'titrevaleur'=>			'',
		'wysiwyg'=>				0,
		'resize'=>				'',
		'htmDefaut'=>			'',
		'oblige'=>				0,
		'disable'=>				0,
		'relation'=>			'',
		'inc'=>					'',
		'unique'=>				'',
		'action'=>				'',
		'index'=>				0,
		'tips'=>				'',
	),
	
	array(name=>'commentaire',titre=>'Commentaire admin.',sqlType=>'text',input=>'textarea',wysiwyg=>'0', 'separateur'=>'CHAMPS ADMIN'),

);
//$C = new SQL($R3); $C->createSQL($R3_data,'1');
//$C = new SQL($R3); $C->addSQL($R3_data);

?>